### ISSUE TITLE
No MMS in 2G

### ISSUE THREAD

**Issue by lascapi** [ubports/messaging-app#17]
I do not receive multimedia text messages (MMS) when cellular data is disabled and when I am connected in 2G. This is working only in 3G/4G. 

I have a LG Nexus5 with Ubuntu15.04(r17) (chanel candidate) and all the apps are up-to-date.

**Comment by Flohack74** [comment]
Well cellular data is necessary to send/receive the MMS, see for example: https://forum.telus.com/t5/Mobility-Services/Why-do-I-need-Cellular-Data-turned-on-to-send-receive-MMS/td-p/39622

But this should work in all modes, 2G, EDGE, 3G, HSDPA, etc...

Please also read this https://en.wikipedia.org/wiki/Multimedia_Messaging_Service fully to understand the service.

**Comment by Flohack74** [comment]
(MMS is in fact not like SMS, instead its a normal TCP/IP driven service, only controlled by SMS messages: 

> An SMS "control message" containing the URL of the content is then sent to the recipient's handset to trigger the receiver's WAP browser to open and receive the content from the embedded URL. Several other messages are exchanged to indicate the status of the delivery attempt.[6] Before delivering content, some MMSCs also include a conversion service that will attempt to modify the multimedia content into a format suitable for the receiver. This is known as "content adaptation".

)

**Comment by lascapi** [comment]
Thank you ! I know that. 
I should get the MMS in 2G, right ? 

And when I'm disconnected, the normal behavior, which I could see on android for example, is to open a connection to receive the mms automatically. Or at least to receive it the next time I connect in 2g/3g, but this is a feature request :)

**Comment by Flohack74** [comment]
Yes in 2G / E display on the mobile phone, WAP/Internet is on, should work ;)

**Comment by lduboeuf** [comment]
maybe this is a related bug https://github.com/ubports/ubuntu-touch/issues/239 , when data is disabled, we should have a sms notification ( at least it is the case on other os phones )

**Comment by lnoble237** [comment]
(on fairphone 2) also do not receive mms when cellular data is turned off, would be good to receive a notification saying an mms had been sent!

**Comment by Flaburgan** [comment]
Yes, +1 on this.

**Comment by lduboeuf** [comment]
+3000 :) , this is something that is known since the beginning, see "current issue" here: https://wiki.ubuntu.com/Touch/Specs/MMSInfrastructure
This is out of my skills :-|

**Comment by Flaburgan** [comment]
Well to be fair I noticed that even with 4G enabled, I received the MMS only if the SMS application is open (and maybe even only when it's foreground, I need to double check). So maybe there are things to do to improve the situation even when network is enabled. But there are too many issues about MMS in several repository, I'm lost :(

**Comment by rik-shaw** [comment]
As of devel channel on 2021-12-17 I can confirm that at least for my carrier (US Mobile, a T-Mobile mvno in the USA), 2G MMS receive does not work but suspect that is because their 2G network is being disabled. So while this is not confirming the "fix", let me explain:

4G receive MMS works.
3G receive MMS fails currently but that is due to needing 2 different APN context (one for "internet" and a different one for "mms"). If I manually apply the `ofono 28` patch and configure my `serviceproviders.xml` APN defaults correctly, then I am able to receive 3G MMS fine with no error. https://github.com/ubports/ofono/pull/28

With 2G, even with the `ofono 28` patch I still get the "oops" message with the download link. So when I get back to 3G or 4G range then I can download successfully.

I suggest we do NOT hold up on this issue because 2G is getting discontinued so it is not necessarily a problem of UT. If someone has 2G Data ability they can test, but I don't think I do and it may be difficult to find a tester.

Regardless, because of the associated patches, MMS is in a much better state. Thanks to everyone!

**Comment by Flohack74** [comment]
Great!

**Comment by rik-shaw** [comment]
I just confirmed that cellular data is not working for me at all with the "not combined 2 different APNs" when in 3G or 2G mode (only in 4G mode). So I think this (of course) confirms why I am not a good tester for checking MMS functionality in 2G mode.
