### ISSUE TITLE
Custom Ringtones For Specific Certain Contacts

### ISSUE THREAD

**Issue by ghost** [ubports/messaging-app#170]
Use case: As someone who goes on pagerduty for work it's important that I can distinguish between pages (required 10 minute resolution time for example) and any old page that I can ignore. The lack of this feature is a blocker for me using Ubuntu Touch, since worst case it ends with me losing my job.

What happens now: all contacts use the same sms ringtone.

What (I think) should happen: I should be able to set a custom ringtone for certain contacts, be it per-contact or via some sort of starred/favorite contact system. A possible nice extra would be a system to override do not disturb settings for contacts as well, so that even if my phone accidentally gets set to silent a message from an important contact would go through.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/170

Sorry for your inconvenience.
