### ISSUE TITLE
Add a quicklink to the users profile in the top menu

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/messaging-app#188]
In the Messaging app, there's no quick or easy way to find out your number, or to share your number, perhaps you could have your own profile in contacts, which would sync with the messaging app, that would allow you to have your profile icon in the top left, next to the "Messages" text, you could tap your pfp, and it would load your contact information in the contacts app?

The signal messenger does something like this, but it shows you your signal profile rather than show's you the contact page in the actual contacts app.

![unnamed](https://user-images.githubusercontent.com/8162805/79078785-987da880-7d02-11ea-8c5c-55b3bd5b0a0a.png)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/188

Sorry for your inconvenience.
