### ISSUE TITLE
No "plus" button into an existing conversation.

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#203]
Dear all,

with my mako, OTA-12, I cannot add a new addressee from an existing conversation. There is no "plus" icon in case one want to add somebody.
Best

**Comment by lduboeuf** [comment]
Was it the case before OTA-12 ?

**Comment by Thieb67k** [comment]
Er... I am not 100% sure but I don't remember I have seen that "plus" previously. I had to create a new message or forward it.

**Comment by Flohack74** [comment]
Is this still relevant?

**Comment by Thieb67k** [comment]
In some cases I feel is more convenient to quickly add someone from an existing conversation, instead of going back then create a new message with the same person plus someone else. But if no one see the point, I will follow the majority ;)
Thanks for taking the time anyway.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/203

Sorry for your inconvenience.
