### ISSUE TITLE
Devel: draft with no contact not saved

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#217]
Create a new message without selecting a contact or a phonenumber.
write a draft message, go back. I would expect to have my previous draft displayed.

**Comment by lduboeuf** [comment]
I remember that i've intentionaly not implemented that as it requires more times, and possible side effects

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/217

Sorry for your inconvenience.
