### ISSUE TITLE
Group text but no group answer

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#223]
Dear all,

When I send a group text, I get each answers into the individual threads, nothing into the group text. Hence, it is often difficult to understand who answered.
I feel it would be easier to : 
- get each answers from the differents penpals into the grouped thread.
-or to have a copy of the grouped text into the threads of the corresponding penpals.
Does that make sense?

Best,

(mako, OTA-12)

**Comment by lduboeuf** [comment]
Yes, this is a long standing bug, there is some started work in lower level, but unfortunatly nobody took it seriously.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/223

Sorry for your inconvenience.
