### ISSUE TITLE
Duplication of attachment

### ISSUE THREAD

**Issue by jezek** [ubports/messaging-app#229]
Copied and rewritten from #175 comment.

Device: FP2
Image: 2020-W35/2

Spotted an attachment (image) duplication. It can be reproduced by:

- start message app in landscape mode.
- start composing new message (+ on top right, swipe from down, tapping on some contact conversation) if any attachments are already there (saved as draft), remove them.
- add a picture from gallery as attachment.
- rotate to landscape.
- add other picture from gallery. (the duplication happens if you choose not to add a picture from gallery and close he gallery with X on top right)

Expectation: 2 image attachments.
Result: 3 image attachments. There is a duplicate of first image.
Note: sometimes the duplication doesn't happen, but most times (7 of 9) it did.

There was another duplication occurrence posted by @spartid in https://github.com/ubports/messaging-app/pull/175#issuecomment-683280406
> Tested with FP2. I could attach a picture (and there was no bad UX with that), but then I unintentionally locked the screen.
> When I went back to my message, the picture was added an other time (there were two attachments of the same picture) !
> However I could suppress them both.

Edit: Renamed title. The duplication can occur without screen rotation. See bellow.

**Comment by ghost** [comment]
@jezek I must add to this that the issue occurred to me without rotating the screen.

**Comment by jezek** [comment]
@spartid I've edited the issue title. You mean, the duplication occurred, how it is written in first post? Can you reproduce how it occurred and write more specific way to reproduce, please?

**Comment by ghost** [comment]
@jezek Sorry for being too vague, it's the nearly first time I contribute otherwise that financially to a libre software project... So here are the steps to reproduce :

1. Lock the rotation
2. Start message app in portrait mode
3. Start composing new message (+ on top right, swipe from down, tapping on some contact conversation) if any attachments are already there (saved as draft), remove them.
4. Add a picture from gallery as attachment
5. Add another picture from gallery as attachment (select the image and confirm selection)

Expected : 2 pictures
What happens : 3 pictures 
Here is a screenshot : 
![screenshot20200903_193358205](https://user-images.githubusercontent.com/68387285/92148448-e3689b80-ee1c-11ea-9fab-1ea03eb0f6f7.png)

**Comment by jezek** [comment]
@spartid Yes, I can replicate, but only when the recipient is filled. If the recipient is blank, the duplication does not occur for me.

**Comment by ghost** [comment]
@jezek I can confirm this.
