### ISSUE TITLE
Enhancement: Delete OTP sms automatically after 24 hours

### ISSUE THREAD

**Issue by likeadragonmaid** [ubports/messaging-app#242]
The title says it all, OTP messages to be deleted after 24 hours to keep inbox clean.

**Comment by lduboeuf** [comment]
Well, this will need lots of work for a special use case, do you know you can delete the Thread instead (swipe right on the thread ) ? ?

**Comment by likeadragonmaid** [comment]
I was thinking we could get something close to this on ubports https://www.xda-developers.com/google-messages-6-7-prepares-automatically-delete-otp-after-24-hours/

**Comment by lduboeuf** [comment]
Is there any specification of OTP sms ?
Seems a mess ( see Standardisation ) : https://en.m.wikipedia.org/wiki/One-time_password

**Comment by lduboeuf** [comment]
What could be less hard to do is delete them at startup time, i don't know if any cron exist for history-service. But we nees to know how can we identify a OTP sms

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/242

Sorry for your inconvenience.
