### ISSUE TITLE
Clean up old audio recorded file

### ISSUE THREAD

**Issue by lduboeuf** [ubports/messaging-app#244]
https://github.com/ubports/messaging-app/blob/xenial/src/audiorecorder.cpp#L164

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/244

Sorry for your inconvenience.
