### ISSUE TITLE
[feature request] access favourite phone numbers

### ISSUE THREAD

**Issue by gbdomubpkm** [ubports/messaging-app#253]
It seems to me that it would be convenient if the favourite (star) phone numbers could be accessed not only by the dialer as it is now but also by the messaging app .

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/253

Sorry for your inconvenience.
