### ISSUE TITLE
Warn user when a recipient doesn't support replies

### ISSUE THREAD

**Issue by Fuseteam** [ubports/messaging-app#262]
Service Providers over here like to send sms advertisements.
as these adverts aren't intended for corrospondence, these smses set the actual advertisers name in the field that is normally used for the sender's telephone number.
we should catch this and prevent the user from replying to the sender, as the advertiser won't receive the reply anyway

**Comment by lduboeuf** [comment]
We already have the logic to check for valid numbers, it shouldn't be that hard to do it

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/262

Sorry for your inconvenience.
