### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#285]
Dear all,

Since I have sent a SMS, today, there is still the text in grey with the loading icon. Yet, the message has been sent: I got the answer.
I was able to reply. I mean the text has been sent and turned green. But the previous text is still grey with the loading icon.

No big deal but strange.
Thanks,

Mako Nexus4, OTA-16, stable channel.

**Comment by lduboeuf** [comment]
Confirmed, i have that from time to time, but hard to reproduce

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/285

Sorry for your inconvenience.
