### ISSUE TITLE
Feature request, Message App -> Archive

### ISSUE THREAD

**Issue by Thieb67k** [ubports/messaging-app#292]
Dear all,
As far as I know, it is not possible to archive sms. Would it be possible to add one extra option with sms we want to see into an archive folder ?
Plus, that could be an interesting feature if you want to delete a full conversation exept 2 or 3 specific messages (?).
Thanks

**Comment by lduboeuf** [comment]
Well i admit, this would be a complex things to do, but who knows if someone want to try :)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/292

Sorry for your inconvenience.
