### ISSUE TITLE
feature request: auto forward SMS, like calls

### ISSUE THREAD

**Issue by cauerego** [ubports/messaging-app#313]
https://t.me/ubports/374232 for more context.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/

Sorry for your inconvenience.
