### ISSUE TITLE
Schedule sms and autoreply

### ISSUE THREAD

**Issue by pysoft13** [ubports/messaging-app#314]
Hi,
Would.be interesting to have new features:
-possibility to schedule sms sending, choice of date n time, recipient and message
-autoreply (rules on date,time,recipient,message content)

**Comment by lduboeuf** [comment]
This is going to be quite a big task, i'm not sure it is easily doable as there is nothing ready for scheduling tasks on UT. But if any volonteers :)

**Comment by pysoft13** [comment]
At least just autoreply should be possible.
With rules on phonenumber, received message content, time and date.

**Comment by lduboeuf** [comment]
yes all is possible, but this is more a matter of time. This can't be done in only few hours

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/317

Sorry for your inconvenience.
