### ISSUE TITLE
[feature request] Option to display Sent time instead of Received timestamp

### ISSUE THREAD

**Issue by olisax** [ubports/messaging-app#345]
Hello!

As during the night I shut down my phone, all messages I received during the night are labelled with the timestamp of next morning, when I turn on the phone.

Could it be possible to add a parameter/option to let the user choose if he wants to display `activeMessage.sentTime` instead of `activeMessage.timestamp` ? :-)

<img src="https://user-images.githubusercontent.com/8749489/180759791-f0b332aa-fd77-4b3c-9f2d-b4ef0d57268c.png" width="300">

**Comment by lduboeuf** [comment]
hello,
I did some tests once, but sort the thread by the sent time was very messy as it is not always set or even sometimes after the received date. I doubt it will be a good option.

**Comment by olisax** [comment]
Ok merci Lionel.

Just thinking about it we could take the minimum between (sent time ; received time), so we are sure we avoid NULL values or incorrect sent date. But it's becoming less intuitive then...

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/319

Sorry for your inconvenience.
