### ISSUE TITLE
Enchancement: need template option for messaging app

### ISSUE THREAD

**Issue by impressstudio** [ubports/messaging-app#35]
It will be great if ubports add template option with add new template for sms

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/35

Sorry for your inconvenience.
