### ISSUE TITLE
dh_install: missing files, aborting

### ISSUE THREAD

**Issue by jonnius** [ubports/messaging-app#43]
When trying to build with crossbuilder (see #42), I get the following error ([Full output on pastbin](https://pastebin.com/GZxUXMdy)):
```
dh_install --fail-missing
dh_install: usr/lib/python3/dist-packages/messaging_app/emulators.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/fixture_setup.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/__init__.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/helpers.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/tests/__init__.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/tests/test_messaging.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/testdata/vcard.vcf exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3/dist-packages/messaging_app/testdata/history.sqlite exists in debian/tmp but is not installed to anywhere
dh_install: missing files, aborting
make[1]: *** [override_dh_install] Error 2
debian/rules:44: recipe for target 'override_dh_install' failed
make[1]: Leaving directory '/home/jonatan/messaging-app'
make: *** [binary] Error 2
debian/rules:20: recipe for target 'binary' failed
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```
Any idea how to fix that?

**Comment by mardy** [comment]
This caused by the code in the [test's cmake file](https://github.com/ubports/messaging-app/blob/xenial/tests/CMakeLists.txt): it is invoking python3 to get a directory, and then runs a command to install the autopilot files into that directory. But in our case, we should skip these steps altogether.

I think you should change [line 75 in the main CMakelists file](https://github.com/ubports/messaging-app/blob/xenial/CMakeLists.txt#L75) to use a cmake option (like "`ENABLE_TESTS`", for example) and then change the `debian/rules` file to properly pass (or not pass) this option based on whether `nocheck` is given. I did something similar (just for a qmake project) [here](https://github.com/ubports/ubuntu-system-settings-online-accounts/commit/9cf9207bdf41580fb580e107ffb5c0d9be59c011#diff-d2b2229a977ef7e99780f2207c29b503).

**Comment by jonnius** [comment]
I am trying to do so (https://github.com/jonnius/messaging-app/commit/7b1803cd0916cf40a467e6e1c496173499f7790b). But I don't know how to pass that variable from debian/rules to the CMakeLists.txt, as there is no dh_auto_configure like in your example.

**Comment by mardy** [comment]
You could copy the whole `dh_auto_configure` block, but actually in this case it's probably better to just add the parameter to the `DEB_CONFIGURE_EXTRA_FLAGS` variable. Something like this should work:
```
ifneq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
    DEB_CONFIGURE_EXTRA_FLAGS += "-DENABLE_TESTS=OFF"
else
    DEB_CONFIGURE_EXTRA_FLAGS += "-DENABLE_TESTS=ON"
endif
```

**Comment by mardy** [comment]
Forget about `DEB_CONFIGURE_EXTRA_FLAGS`, it looks like it's an old variable no longer supported. So indeed, you'll have to add a `dh_auto_configure` block.

**Comment by jonnius** [comment]
I tried (https://github.com/jonnius/messaging-app/commit/876c64e896686b0fdadeec89d545b8edb5bdb1f3) but now getting an error there ([pastbin](https://pastebin.com/80F59Mir)). I think it would need to be a bit different for cmake, but I have no glue.

**Comment by mardy** [comment]
I added a few comments on that commit, that should work.

**Comment by jonnius** [comment]
Thanks! It works now.
