### ISSUE TITLE
Selecting a contact in Messages is inconsistent with Contacts

### ISSUE THREAD

**Issue by Benni777** [ubports/messaging-app#45]
Environment:
- Nexus 4 (mako), 16 GB
- Ubuntu 16.04 (2018-09-17)
- Channel: dev

Steps:
1. Open Messages
2. Touch + to add a message
3. Touch + to add a contact

Expected
- List of contacts to select a contact as in contacts

Actual
- List of contacts to select a contact
- Pseudo contact at first to create a new contact
- first non-pseudo contact has a red border and different font color

Notes:
1. The first non-pseudo contacts shall not have this red border and different font color.
2. If it is necessary to be able to create a new contact in this context, then a new contact shall be created consistent as in Contacts.
3. In Contacts you have to swipe from the bottom to the top to create a new contact. Also to touch a + in the right top corner could be an alternative for swiping from the bottom to the top.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/45

Sorry for your inconvenience.
