### ISSUE TITLE
sync sms to nextcloud

### ISSUE THREAD

**Issue by Thatoo** [ubports/messaging-app#74]
It would be nice to be able to backup our sms into our nextcloud.
Nextcloud has an app that provides a webinterface to display our SMS conversations, https://github.com/nextcloud/ocsms
And an android app exist to push sms to nextcloud, https://github.com/nerzhul/ncsms-android

It would be nice to have that feature in UT too, I think.

What do you think?

**Comment by krille-chan** [comment]
I fully agree, this would be great. When I have time I would like to try this task.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/74

Sorry for your inconvenience.
