### ISSUE TITLE
input from content hub not working if recipient field is empty

### ISSUE THREAD

**Issue by Danfro** [ubports/messaging-app#84]
**Steps to reproduce:**
1. copy content i.e. a phone number from dialer
2. open messaging app
3. swipe up or tap + to start composing a new message
4. tap and hold in the recipient field at the top

**expected behaviour:**
Context menu opens and content can be copied into the field. Regardless if there is content present in that field and regardless where you tap within the field.

**actual behaviour:**
a) If no content is present pasting of content does not work at all
b) If content is present only when tap and hold on that content the context menu opens and content can be pasted.

**Comment by krille-chan** [comment]
This complete TextField seems to be non-optimized. I have done a workaround so that you can long press for the context menu everywhere as long as there is no content. I guess this will fix 99% of the use cases of pasting text in this TextField. In the future we should replace this TextField by something more stable but I would wait for this until we have a new UI toolkit.
