### ISSUE TITLE
Not all phone numbers matching a query are displayed in Messages

### ISSUE THREAD

**Issue by Benni777** [ubports/messaging-app#98]
Environment
- Nexus 4 (mako), 16 GB
- Ubuntu 16.04 (2018-09-05)
- Channel: dev

Steps
1. Open Messages
2. Select [+] to open a new Message thread
3. Enter the first two dgits of the phone number (01)

Actual
- Three contacts starting with 017 will be suggested addidtional to phone numbers starting 01 and a third digit which is not 7

Steps
4. Enter "7" as third digit (017)

Expected
- Three phone numbers starting with 017 will be suggested

Actual
- One phone number starting with 017 will be suggested

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/messaging-app/-/issues/98

Sorry for your inconvenience.
